version: '1'

services:
  sonarqube:
    depends_on:
    - db
    image: sonarqube:latest
    restart: always
    ports:
    - "9000:9000"
    - "9092:9092"
    environment:
      SONARQUBE_JDBC_USERNAME: <sonar-user>
      SONARQUBE_JDBC_PASSWORD: <password>
      SONARQUBE_JDBC_URL: jdbc:mysql://apseo-qe-sonar/sonar?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true
  db:
    image: mysql/mysql-server:5.7
    restart: always
    ports:
    - "3306:3306"
    environment:
    - MYSQL_USER=<mysql_user>
    - MYSQL_ROOT_PASSWORD=<password>
    - MYSQL_PASSWORD=<password>
    - MYSQL_DATABASE=sonar
    volumes:
    - /home/eass-build/mysql/data:/var/lib/mysql
    - /home/eass-build/mysql/config:/etc/mysql